### ISSUE TITLE
Rename to with-bluetooth-classic?

### ISSUE THREAD

**Issue by thgh** [amitferman/with-rn-bluetooth-classic#1]
Installing this plugin shows a different plugin name (with -rn-) while the readme does not have that.
<img width="291" alt="Screenshot 2021-12-19 at 15 40 25" src="https://user-images.githubusercontent.com/1109982/146678937-82f016fb-fc92-43dd-a4c0-5e8a5a3a91ea.png">

**Comment by amitferman** [comment]
Thanks for pointing out this issue. The plugin installation is working correctly; the issue is in the readme. I published a fix to the documentation, though you shouldn't have to update the plugin in your project. I chose not to rename to `with-bluetooth-classic` since the current naming aligns with the Expo team's naming conventions (e.g., `with-rn-firebase').

**Comment by thgh** [comment]
The plugin works wonderfully! Thank you very much! I knew nothing about bluetooth two weeks ago and was able to connect to a device in no time using this plugin 🚀
