### ISSUE TITLE
Reload app keeps Bluetooth connection active

### ISSUE THREAD

**Issue by thgh** [amitferman/with-rn-bluetooth-classic#2]
Reproduction
* `expo run:android`
* Press "a" in terminal (Open app on Android device)
* Connect to a bluetooth device in app on Android
* Press "r" in terminal (Reload app)
* Connect to the same bluetooth device in app on Android

Expected: connects to the device
Actual: `[Error: java.io.IOException: read failed, socket might closed or timeout, read ret: -1]`

It seems like the "Reload app" command does not cleanup connection resources. I see on my BT device that it stays connected after the app reloaded.

Looking at the source code, this is probably not an issue within this project.

**Comment by amitferman** [comment]
It appears that BT sockets aren't being cleaned up with reload, as you suggest. I found this GH [issue](https://github.com/rusel1989/react-native-bluetooth-serial/issues/15) but it seems to require modifying Android source code.

Are you able to reuse an existing socket (by checking if connected in advance) rather than automatically produce a new socket?
